[package]
name = "bj_basic_strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
wasm-bindgen = "0.2.100"
proc_macros = { git = "https://github.com/lkbhargav/proc_macros.git", rev = "c356edcdc2c887e6820c230c92884504e52556cb" }
syn = "2.0.98"
rand = "0.9.0"
